export enum Identifiers {
  COMPLIANCES = 'COMPLIANCES',
  FINRA = 'FINRA',
  UPDATE = 'UPDATE',
  COMPANY_TICK_SYMBOLS = 'COMPANY_TICK_SYMBOLS',
  SENIOR_POLITICAL_FIGURE = 'SENIOR_POLITICAL_FIGURE',
}
