import {
  Add,
  AddBeneficiary,
  AddUser,
  Alert,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Bank,
  Calendar,
  Checkbox,
  CheckboxUnchecked,
  CircleAlert,
  CircleChevron,
  Copy,
  Disabled,
  Down,
  Edit,
  EyeHide,
  EyeVisible,
  File,
  FriendsAndFamily,
  Gift,
  HamburgerClose,
  HamburgerOpen,
  HelpAndSupport,
  Info,
  Link,
  Loading,
  LoadingHalf,
  LoadingSpinner,
  Mailbox,
  MoreMenu,
  Notification,
  NotificationBell,
  Percent,
  RecurringBig,
  Refresh,
  Search,
  Share,
  SignOut,
  Tick,
  Trash,
  Trophy,
  Up,
  Upload,
} from './icons';

export const icons = {
  add: Add,
  addUser: AddUser,
  alert: Alert,
  arrowDown: ArrowDown,
  arrowLeft: ArrowLeft,
  arrowUp: ArrowUp,
  arrowRight: ArrowRight,
  bank: Bank,
  calendar: Calendar,
  checkbox: Checkbox,
  disabled: Disabled,
  down: Down,
  edit: Edit,
  eyeHide: EyeHide,
  eyeVisible: EyeVisible,
  hamburgerClose: HamburgerClose,
  hamburgerOpen: HamburgerOpen,
  info: Info,
  link: Link,
  loading: Loading,
  loadingHalf: LoadingHalf,
  loadingSpinner: LoadingSpinner,
  mailbox: Mailbox,
  moreMenu: MoreMenu,
  refresh: Refresh,
  search: Search,
  share: Share,
  trash: Trash,
  trophy: Trophy,
  up: Up,
  upload: Upload,
  file: File,
  percent: Percent,
  tick: Tick,
  circleAlert: CircleAlert,
  circleChevron: CircleChevron,
  notificationBell: NotificationBell,
  notification: Notification,
  checkboxUnchecked: CheckboxUnchecked,
  friendsAndFamily: FriendsAndFamily,
  signOut: SignOut,
  helpAndSupport: HelpAndSupport,
  addBeneficiary: AddBeneficiary,
  gift: Gift,
  copy: Copy,
  recurringBig: RecurringBig,
};

export const sizes = {
  xs: 21,
  s: 24,
  m: 32,
  l: 40,
  xl: 48,
  xxl: 96,
};
