export enum Identifiers {
  PROFILE_VERIFICATION_FAILED = 'PROFILE_VERIFICATION_FAILED',
  STAKEHOLDER_VERIFICATION_FAILED = 'STAKEHOLDER_VERIFICATION_FAILED',
  TRUSTEES_VERIFICATION_FAILED = 'TRUSTEES_VERIFICATION_FAILED',
  STAKEHOLDER_LIST = 'STAKEHOLDER_LIST',
  PROFILE_INFORMATION = 'PROFILE_INFORMATION',
  PROFILE_MANUAL_REVIEW = 'PROFILE_MANUAL_REVIEW',
  STAKEHOLDER_MANUAL_REVIEW = 'PROFILE_MANUAL_REVIEW',
  PROFILE_ADDRESS = 'PROFILE_ADDRESS',
  ID_SCAN = 'ID_SCAN',
  IDENTIFICATION_DOCUMENTS = 'IDENTIFICATION_DOCUMENTS',
}
