export enum Identifiers {
  VERIFICATION_FAILED = 'PROFILE_VERIFICATION_FAILED',
  PROFILE_INFORMATION = 'PROFILE_INFORMATION',
  PROFILE_ADDRESS = 'PROFILE_ADDRESS',
  ID_SCAN = 'ID_SCAN',
  IDENTIFICATION_DOCUMENTS = 'IDENTIFICATION_DOCUMENTS',
}
