enum Screens {
  BottomNavigator = 'BottomNavigator',
  SignUp = 'SignUp',
  SignIn = 'SignIn',
  FirstStepLayoutScreen = 'FirstStepLayoutScreen',
  BlackForm = 'BlackForm',
  Dashboard = 'Dashboard',
  REIT = 'REIT',
  EducationStack = 'EducationStack',
  EducationMainScreen = 'EducationMainScreen',
  BlogScreen = 'BlogScreen',
  Notifications = 'Notifications',
  Settings = 'Settings',
  WebViewContent = 'WebViewContent',
  Onboarding = 'Onboarding',
  ResetPassword = 'ResetPassword',
  ManageAccountMainScreen = 'ManageAccountMainScreen',
  ManageAccount = 'ManageAccount',
  Investing = 'Investing',
  AddBeneficiary = 'AddBeneficiary',
  BankAccount = 'BankAccount',
  KYCFail = 'KYCFail',
  Locked = 'Locked',
  NotificationDetails = 'NotificationDetails',
}

export default Screens;
