export enum Identifiers {
  ORIGINAL_EMPLOYMENT_DETAILS = 'ORIGINAL_EMPLOYMENT_DETAILS',
  UPDATE_EMPLOYMENT_STATUS = 'UPDATE_EMPLOYMENT_STATUS',
  UPDATE_EMPLOYMENT_DETAILS = 'UPDATE_EMPLOYMENT_DETAILS',
}
