export enum Identifiers {
  INITIAL_INVESTMENT = 'INITIAL_INVESTMENT',
  VERIFY_INVESTMENT = 'VERIFY_INVESTMENT',
  RECURRING_INVESTMENT = 'RECURRING_INVESTMENT',
  RECURRING_AMOUNT_INVESTMENT = 'RECURRING_AMOUNT_INVESTMENT',
  RECURRING_INTERVAL = 'RECURRING_INTERVAL',
  RECURRING_DEPOSIT_SCHEDULE = 'RECURRING_DEPOSIT_SCHEDULE',
  RECURRING_DATES = 'RECURRING_DATES',
  RECURRING_DIVIDEND_REINVESTING = 'RECURRING_DIVIDEND_REINVESTING',
  AGREEMENTS = 'AGREEMENTS',
}
